package cr.brainstation.bsfinalproject.constants;

/**
 * Constant strings used in the ResourceBundle as keys for retrieving the resource.
 */
public interface ResourceBundleConstants {

    String EMPTY_PRODUCT_NAME_MSG = "EMPTY_PRODUCT_NAME_MSG";
    String EMPTY_PRODUCT_IMAGE_URL_MSG = "EMPTY_PRODUCT_IMAGE_URL_MSG";
    String EMPTY_USER_EMAIL_MSG = "EMPTY_USER_EMAIL_MSG";
    String EMPTY_USER_NAME_MSG = "EMPTY_USER_NAME_MSG";
    String EMPTY_ADDRESS_MSG = "EMPTY_ADDRESS_MSG";
    String EMPTY_USER_PASSWORD_MSG = "EMPTY_USER_PASSWORD_MSG";
    String EMPTY_CREDIT_CARD_TOKEN_MSG = "EMPTY_CREDIT_CARD_TOKEN_MSG";
    String EMPTY_CREDIT_CARD_BRAND_MSG = "EMPTY_CREDIT_CARD_BRAND_MSG";
    String EMPTY_CREDIT_CARD_EXPIRATION_DATE_MSG = "EMPTY_CREDIT_CARD_EXPIRATION_DATE_MSG";
    String EMPTY_CREDIT_CARD_USER_MSG = "EMPTY_CREDIT_CARD_USER_MSG";

    String INVALID_CREDIT_CARD_FOUR_DIGITS_MSG = "INVALID_CREDIT_CARD_FOUR_DIGITS_MSG";

    String USER_NOT_FOUND_MSG = "USER_NOT_FOUND_MSG";
    String ADDRESS_NOT_FOUND_MSG = "ADDRESS_NOT_FOUND_MSG";
    String CREDIT_CARD_NOT_FOUND_MSG = "CREDIT_CARD_NOT_FOUND_MSG";

    String ADDRESS_FOR_USER_NOT_AUTHORIZED_MSG = "ADDRESS_FOR_USER_NOT_AUTHORIZED";
    String CREDIT_CARD_FOR_USER_NOT_AUTHORIZED_MSG = "CREDIT_CARD_FOR_USER_NOT_AUTHORIZED_MSG";

    String USER_ALREADY_EXISTS_MSG = "USER_ALREADY_EXISTS_MSG";

}
